spring.application.name=sae-register

# ── Serveur ───────────────────────────────────────────────────────────────────
server.port=8080

# ── MySQL Aiven ───────────────────────────────────────────────────────────────
spring.datasource.url=jdbc:mysql://mysql-saeregister-sae-register.g.aivencloud.com:15758/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ── JPA / Hibernate ───────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ── Upload fichiers ───────────────────────────────────────────────────────────
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB